name: flutter_skywalker_core
description: The core to NewGo Flutter apps
version: 1.0.0
author: Yehoshua Oliveira <ioxua.oliveira@gmail.com>
homepage: http://newgo.com.br

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_masked_text: ^0.8.0
  validators: ^2.0.0

  # Okay, so for some reason the official repository has some _curious_ decisions.
  # I'm going fix these things and commit to my personal fork.
  # When the time comes, it is better to depend on the official repo tho
  flutter_platform_widgets: ^0.12.0
    #git: https://github.com/ioxua-os/flutter_platform_widgets.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
